apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ghue4urun-java-quarkus-gitops
  description: This is GitOps manifest for ghue4urun-java-quarkus   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=ghue4urun-java-quarkus
    backstage.io/kubernetes-id: ghue4urun-java-quarkus 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: tnevrlka-rhtap/ghue4urun-java-quarkus-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ghue4urun-java-quarkus
